spring:
  profiles:
    active: EN,dog,prod
guru:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: YmlSomeDBUrl

---
spring:
  profiles: prod
guru:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmlProdSomeDBUrl